FROM nginx:1.25.2 as builder

COPY rd-1/rd-1.nl/rd-1-nginx-proxy.conf /etc/nginx/conf.d/rd-1.conf
COPY rd-1/rd-1.nl/certs /etc/nginx/certs/rd-1/
# COPY rd-2/rd-2.nl/rd-2-nginx-proxy.conf /etc/nginx/conf.d/rd-2.conf
