FROM owncloud/server:latest as builder

RUN apt update \
    && apt install -y git make

# it needs the certs from all mesh hosts
COPY tests/docker/oc-1/oc-1.nl/certs/cert.pem /usr/share/ca-certificates/rd-mesh/oc-1.pem
COPY tests/docker/oc-2/oc-2.nl/certs/cert.pem /usr/share/ca-certificates/rd-mesh/oc-2.pem

RUN echo 'rd-mesh/oc-1.pem' >> /etc/ca-certificates.conf \
    && echo 'rd-mesh/oc-2.pem' >> /etc/ca-certificates.conf \
    && update-ca-certificates \
    && export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

# Add the Collaboration app from local source, includes using the make buildapp-test target to simulate an actual release version
# Install the data migration file required  for the tests
# Install the pre start server script that activates the app
# Install integration tests' requirements
RUN mkdir -p /tmp/collaboration
COPY . /tmp/collaboration
RUN mkdir -p /var/www/owncloud/apps \
    && cd /tmp/collaboration \
    && make -e version=test buildapp-tests \
    && tar xvf /tmp/collaboration/build/artifacts/app/collaboration_test.tar.gz -C /var/www/owncloud/apps \
    && cp /var/www/owncloud/apps/collaboration/tests/docker/integration-tests/Version20240718000002.php /var/www/owncloud/apps/collaboration/appinfo/Migrations \
    && cp /var/www/owncloud/apps/collaboration/tests/docker/oc-1/10-collaboration-app.sh /etc/pre_server.d \
    && mv /var/www/owncloud/apps/collaboration/appinfo/routes.php /var/www/owncloud/apps/collaboration/appinfo/routes-main.php \
    && cp /var/www/owncloud/apps/collaboration/tests/docker/integration-tests/src/tests/routes.php /var/www/owncloud/apps/collaboration/appinfo/routes.php \
    && cp /var/www/owncloud/apps/collaboration/tests/docker/integration-tests/src/tests/ExternalApiRoute.php /var/www/owncloud/apps/collaboration/lib/ExternalApiRoute.php

ENV DEBUG=true
