FROM nginx:1.25.2 as builder

COPY oc-1/oc-1.nl/oc-1-nginx-proxy.conf /etc/nginx/conf.d/oc-1.conf
COPY oc-1/oc-1.nl/certs /etc/nginx/certs/oc-1/
# COPY oc-2/oc-2.nl/oc-2-nginx-proxy.conf /etc/nginx/conf.d/oc-2.conf
