name: PHPUnit

on: [push]

jobs:
  integration-tests:
    runs-on:
      ubuntu-latest
    env:
      # the current branch
      BRANCH: ${{ github.ref_name }}

    steps:
      - name: Checkout
        # not compatible with actions/checkout@v4
        uses: actions/checkout@v3
    
      # the docker compose setup
      - name: docker-compose-setup
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: tests/docker/docker-compose-github.yaml
          service: integration-tests
          command: /tmp/tests/tests.sh
