name: PHP Codesniffer
# Please use the same settings as make lint-check-errors.
# See: https://github.com/marketplace/actions/php-code-sniffer-php-actions
#
# Note: Putting more than one sources in path (like: 'path: appinfo/ lib/ templates/') doesn't seem to work.
#       So we split this into separate steps.
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6

      - name: PHP Code Sniffer appinfo
        uses: php-actions/phpcs@v1
        with:
          php_version: 7.4
          version: 3.7.2
          standard: PSR12
          warning_severity: 0
          path: appinfo/

      - name: PHP Code Sniffer lib
        uses: php-actions/phpcs@v1
        with:
          php_version: 7.4
          version: 3.7.2
          standard: PSR12
          warning_severity: 0
          path: lib/

      - name: PHP Code Sniffer templates
        uses: php-actions/phpcs@v1
        with:
          php_version: 7.4
          version: 3.7.2
          standard: PSR12
          warning_severity: 0
          path: templates/
