FROM owncloud/server:latest as builder

RUN apt update \
    && apt install -y git make

# it needs the certs from all mesh hosts
COPY tests/docker/oc-1/oc-1.nl/certs/cert.pem /usr/share/ca-certificates/rd-mesh/oc-1.pem
COPY tests/docker/oc-2/oc-2.nl/certs/cert.pem /usr/share/ca-certificates/rd-mesh/oc-2.pem

RUN echo 'rd-mesh/oc-1.pem' >> /etc/ca-certificates.conf \
    && echo 'rd-mesh/oc-2.pem' >> /etc/ca-certificates.conf \
    && update-ca-certificates \
    && export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

# Add the Invitation app from local source, includes using the make buildapp-test target to simulate an actual release version
# And install the data migration file required  for the tests
# And install the pre start server script that activates the app
RUN mkdir -p /tmp/invitation
COPY . /tmp/invitation
RUN mkdir -p /var/www/owncloud/apps \
    && cd /tmp/invitation \
    && make -e version=test buildapp-tests \
    && tar xvf /tmp/invitation/build/artifacts/app/invitation_test.tar.gz -C /var/www/owncloud/apps \
    && cp /var/www/owncloud/apps/invitation/tests/docker/integration-tests/Version20231130125301.php /var/www/owncloud/apps/invitation/appinfo/Migrations \
    && cp /var/www/owncloud/apps/invitation/tests/docker/oc-1/10-invitation-app.sh /etc/pre_server.d

ENV DEBUG=true
